### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'parent')

### ISSUE THREAD

**Issue by kodcuserkan** [WebDevStudios/nextjs-wordpress-starter#1009]
After installing the libs, when I run `yarn dev` I got `TypeError: Cannot set properties of undefined (setting 'parent')` 
<img width="780" alt="Screen Shot 2022-05-09 at 23 12 20" src="https://user-images.githubusercontent.com/48566149/167489771-7ae7381d-0ac2-41f9-a466-059d3817c90a.png">

**Comment by paulpichot** [comment]
I have the same problem. Did you find a solution ?

**Comment by emilse-webdev** [comment]
react and react-dom 18 returns that error, using v17 solves the issue.

**Comment by ferremek** [comment]
Hi guys, did you figure out how to fix this error?

I have followed the official docs twice now and still get this error. I have node **v16.15.0** and npm **8.5.5**. I have the same package.json file as the main repo and it uses react and react-dom v17.0.2.

**Comment by sloyer** [comment]
The latest update in tailwindcss broke it downgrade it to 3.0.23

**Comment by ferremek** [comment]
@sloyer Yes, that is it! Thanks a lot 😄

**Comment by kodcuserkan** [comment]
I left the project after trying hard do make it up but fail :(

**Comment by mrEckendonk** [comment]
opened a new issue, https://github.com/WebDevStudios/nextjs-wordpress-starter/issues/1059, and closed it referring to this 

downgrading tailwind to 3.0.23 did not fix this issue

**Comment by apatwary12** [comment]
Downgrading tailwindcss to 3.0.23 and running npm i --legacy-peer-deps does not fix this issue.

**Comment by mrEckendonk** [comment]
This issue can temporarily be resolved by using the correct branch with the hotfix suggested by @itsamoreh 
Downgrading tailwind to 3.0.23 won't fix due to [dependabot[bot] updates on the main branch. 

Follow these steps:

```
git clone git@github.com:WebDevStudios/nextjs-wordpress-starter.git
cd nextjs-wordpress-starter
git branch fix/downgrade-tailwindcss
npm i 
```

** follow instructions to set up back & frontend.

`npm run dev`

Have fun

**Comment by adam-ainsworth** [comment]
I've been battling with this error too, but I found that using Node 16, downgrading react and react-dom to 16.14.0 and tailwindcss to 3.0.22 I was able to get it to build.

It's not sustainable but it'll do the job for a while.

WDS should either update the project or take down this tutorial if it's no longer supported.

**Comment by kodcuserkan** [comment]
Since I do not (and will not) work with this project anymore closing this.
