### ISSUE TITLE
Possible collaboration with WP Engine

### ISSUE THREAD

**Issue by claytoncollie** [WebDevStudios/nextjs-wordpress-starter#147]
Hi everyone! My team and I have been following your progress and are very thankful for your hard work. This repo is amazing and exactly what the entire WP community needs to push the adoption of NextJS and headless development. We will do our best to find issues that we can help with and submit PRs in the future.

This issue is more of a suggestion to contact WP Engine about their serverless hosting solution that is set to launch in the near future. They are building out some features that you all could help with or take from. I think there is a ton of overlap on what is in this repo and what they are working on.

https://github.com/wpengine/headless-framework

**Comment by gregrickaby** [comment]
@claytoncollie I've been working with Annan Patel this week on your Headless Framework. Specifically https://github.com/wpengine/headless-docs

We should def talk... could you please schedule a call? https://calendly.com/wds-greg

**Comment by gregrickaby** [comment]
@claytoncollie Good news. We've started collaboration with WPE this week and we're looking forward partnering with them. Thank you for the note.
