### ISSUE TITLE
Update WP GraphQL on WordPress Backend

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/nextjs-wordpress-starter#16]
The WordPress backend the WebDevStudios team is using for development at https://nextjs.wpengine.com/ is running WP GraphQL version `0.9.1` while the [latest version](https://github.com/wp-graphql/wp-graphql/releases) at the time this issue is being written is `0.12.1`.

This update adds the `locations` field in the `menus` query, which is relevant to #4

**Comment by gregrickaby** [comment]
@salcode Thank you. This is done:

![screenshot](https://dl.dropbox.com/s/aye3f26fzry133q/Screen%20Shot%202020-08-29%20at%207.13.54%20AM.png?dl=0)

![screenshot](https://dl.dropbox.com/s/2h710lde0ja2vvs/Screen%20Shot%202020-08-29%20at%207.13.30%20AM.png?dl=0)
