### ISSUE TITLE
Fetch hierarchical posts

### ISSUE THREAD

**Issue by rodrigo-arias** [WebDevStudios/nextjs-wordpress-starter#214]
Hi guys, I'm using your repo as a reference for a WordPress and Next implementation. Thank you for all the work you are doing, it is a great contribution.

**Description**
I am having some issues fetching hierarchical posts. You are fetching posts by ID from the URI if it is hierarchical, from the SLUG if it is not [here](https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/staging/api/wordpress/_global/getPostTypeStaticPaths.js#L24).

And then you are splitting the path [here](https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/staging/api/wordpress/_global/getPostTypeStaticPaths.js#L51) to return it in the **getStaticPaths** function.

All of that makes perfect sense. But I'm seeing that if you have a URI for example `people/name`, you return the path as an array `['people', 'name']` and then in the `params` attribute of **getStaticProps** [here](https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/staging/pages/team/%5B%5B...slug%5D%5D.js#L128), it receives only `slug: ['name']`

For some reason in the background I am losing one of the parameters.

**Notes**
I found some discussions that could be related, I add the references in case they are useful:
https://github.com/vercel/next.js/discussions/14150
https://github.com/vercel/next.js/discussions/11272
https://github.com/vercel/next.js/discussions/11738

I would like to know if it was something that you were also experiencing or maybe I am doing something wrong. Thanks

**Comment by gregrickaby** [comment]
@rodrigo-arias Hey thank you so much for checking out the starter and submitting feedback.

I _think_ I'm following along with your issue, and I tried to replicated it:

1. I created a new page "Careers"
2. Under Page --> Attributes, I set the Parent --> About
3. I published Careers
4. I added it to the Primary menu
5. I clicked on "Careers" from the menu dropdown on the frontend

It displays for me: https://nextjs-wordpress-starter-develop.vercel.app/about/careers

Could you provide any more details about how your have your site configured? I'll do my best to help out.
