### ISSUE TITLE
Unable to install wordpress theme

### ISSUE THREAD

**Issue by wanderingcoderr** [WebDevStudios/nextjs-wordpress-starter#251]
Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

If you leave out sections there is a high likelihood it will be moved to our [GitHub Discussions](https://github.com/WebDevStudios/nextjs-wordpress-starter/discussions).

Not able to add theme to the Wordpress localwp

**To Reproduce**
1.Followed all the steps till setting up Wordpress using localwp.
2. Searched for a theme in admin dashboard.
3. Clicked on install theme
4. Getting the error "installation failed could not create directory"

**Expected behavior**
Theme should be installed for the wordpress

**Screenshots**
![image](https://user-images.githubusercontent.com/38850666/109535116-2e205300-7ae2-11eb-9c16-fa3c0e6acdb7.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome

**Additional context**
The localwp creates folder in C:\Users\<USER>\Local Sites 
The permissions of the folder are Readonly is it due to this?
Can you please let me know a way to change the permissions of the folder on windows

**Comment by gregrickaby** [comment]
@wanderingcoderr What happens when you activate the WDS Headless Theme? https://github.com/WebDevStudios/nextjs-wordpress-starter/wiki/Backend-Setup#step-3-activate-the-wds-headless-theme

**Comment by wanderingcoderr** [comment]
@gregrickaby I tried searching for it but it shows no theme found.

![image](https://user-images.githubusercontent.com/38850666/109545506-f1a72400-7aee-11eb-837f-28a21ecb70a5.png)

**Comment by gregrickaby** [comment]
@wanderingcoderr You need to clone our theme. See [this step in our Wiki](https://github.com/WebDevStudios/nextjs-wordpress-starter/wiki/Backend-Setup#step-2-clone-the-nextjs-wordpress-repo).

**Comment by wanderingcoderr** [comment]
@gregrickaby  already did that, 

clone it in the "C:\Users\<USER>\Local Sites\<SITE>\app\public\wp-content" right? 
Is there something I'm missing?

![image](https://user-images.githubusercontent.com/38850666/109546281-fb7d5700-7aef-11eb-9e09-80afd48c1f4c.png)

**Comment by wanderingcoderr** [comment]
@gregrickaby  also can you help with what should be done on windows for 
"rm -rf wp-content && git clone git@github.com:WebDevStudios/nextjs-starter-wordpress.git wp-content"

can we manually delete the folder and then clone the repo in it?

**Comment by gregrickaby** [comment]
@wanderingcoderr Looks like you cloned the wrong Git repository. 

Should be: git clone git@github.com:WebDevStudios/nextjs-starter-wordpress.git

1. You should delete `/wp-content`. 
2. run `git clone git@github.com:WebDevStudios/nextjs-starter-wordpress.git wp-content`

Then you should see the WDS Headless Theme

**Comment by wanderingcoderr** [comment]
@gregrickaby  oh yes, my bad. Got confused with the names! 
Its working fine now , Thanks!
