### ISSUE TITLE
Back-end Connection to WordPress

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#33]
Investigate some options for querying WordPress. 

**Why?**

One of the biggest pain points during the OB/BRI project was querying data via GraphQL. While it was great to query exactly what we wanted, it was also a huge PITA. If the client changes field requirements, Rebekah had to update dozens of queries. Also, even with heavy in-memory caching like Redis? WordPress + WP GraphQL would fall flat on its face and throw 5xx errors during builds.
 
**Axios**

This works. It's easy. It's fast and cheap. But there's no caching, and it can make WordPress fall on its face during a build.

**Apollo Client**

Built for GraphQL queries and also can handle global state management. It also supports in-memory caching.

**Relay**

Like Apollo, handles queries and state management. I've read that it's more complex to setup and maintain.

**SQL**

Query MySQL directly? Everything listed above is just middleware. Why not take advantage of database built for this sort of thing. 

**Server Components**

While this tech is just in the planning stages, it's interesting. https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html

**Comment by gregrickaby** [comment]
@ravewebdev Quick update...

I played around with both Apollo and MySQL. I really liked Apollo and merged it into `staging`. 

I also played with MySQL and got it to work locally (See #35) I did determine that due to IP address restrictions when accessing WPE's remote database, MySQL not a viable solution.

**Comment by ravewebdev** [comment]
I've hit some blocking issues with WP GraphQL when querying on pages set as front page and/or posts page, so that piece is on hold until I get some workarounds and/or fixes:
https://github.com/wp-graphql/wp-graphql/issues/1639
https://github.com/wp-graphql/wp-graphql/issues/1641

**Comment by ravewebdev** [comment]
FYI, I'm encountering some weird issues one some pages. It seems to be a [known issue with the WP GraphQL Gutenberg plugin](https://github.com/pristas-peter/wp-graphql-gutenberg/issues/63) and is likely due to a page using a block that our theme does not support.

**Comment by ravewebdev** [comment]
I've opened a [new issue with WP GraphQL for slug collisions](https://github.com/wp-graphql/wp-graphql/issues/1695). On a previous project we noticed that if posts of different types share a slug (but not the entire URI), the individual post type queries don't behave as expected. Until/unless there is a fix, it's best to ensure not posts (of any type) share slugs.

**Comment by ravewebdev** [comment]
All functionality is in place and functional at this time (as far as WP connection is concerned). I will create new tasks for outstanding issues, such as those noted above in this thread.
