### ISSUE TITLE
Application Password Support

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#36]
Rather than deal with GraphQL JWT stuff...let's leverage Application Password support, now standard in WordPress 5.6 and WP GraphQL.

**Requirements**

- Start by reading the official [Integration Guide](https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/)
- View WP GraphQL's application password [PR #1529](https://github.com/wp-graphql/wp-graphql/pull/1529) (merged back in Oct)
- Then use the generated user/pass located in `1password --> Next.js Starter --> WordPress Application Password`
- Finally, create an authenticated connection using Apollo

**Comment by gregrickaby** [comment]
@ravewebdev I've created the application password and the ENV vars on Vercel. Just run `vercel env pull` to get them.

I also tested using Insomia, and it appears to be working.

**Comment by ravewebdev** [comment]
This functionality is not working with the current release of WP GraphQL (v1.1.2) but [the issue has been addressed](https://github.com/wp-graphql/wp-graphql/issues/1689) and will hopefully be included in an upcoming release. So this is on hold for now.

**Comment by ravewebdev** [comment]
Application password handling was implemented as part of #118.
