### ISSUE TITLE
Add handling for image in ACF Media Text block

### ISSUE THREAD

**Issue by ravewebdev** [WebDevStudios/nextjs-wordpress-starter#378]
The `AcfBlockMediaText` component is overriding the image with an empty object currently:

```
// TODO: Query the DB for the image ID and replace the attributes.data with the correct information.
  attributes.data = {
    ...attributes.data,
    image: {}
  }
```

**Comment by sloyer** [comment]
Thanks for this =)

I have a Gatsby solution that may be able to be converted over. 

https://gist.github.com/sloyer/83416d9ed40881044b9901d7483b776f
https://gist.github.com/sloyer/3b03941a255eb0038e5f25244028537a

**Comment by sloyer** [comment]
We took a jab at converting what we have, i think i need to convert to use getstaticprops, as Im able to console out img and get the return path in the console but cant get it to render.

Also im not sure how this reacts to having multiple of the same block on the page, i had weird results but it could be my environment. 

AcfBlockMediaText.js - https://gist.github.com/sloyer/58d46a1aa983f49199e5cd192332de9c
getImg.js - https://gist.github.com/sloyer/717ac56de6f72e1bf3343ed6fd495959
