### ISSUE TITLE
Vercel Fresh Build install failure

### ISSUE THREAD

**Issue by jahzlariosa** [WebDevStudios/nextjs-wordpress-starter#381]
Tried spinning up a fresh install

and I get this on Vercel

`

19:29:35.331 | > Build error occurred
-- | --
19:29:35.338 | TypeError: Cannot read property 'split' of undefined
19:29:35.338 | at Object.<anonymous> (/vercel/workpath0/next.config.__vercel_builder_backup__.js:3:52)
19:29:35.338 | at Module._compile (internal/modules/cjs/loader.js:1063:30)
19:29:35.338 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
19:29:35.338 | at Module.load (internal/modules/cjs/loader.js:928:32)
19:29:35.338 | at Function.Module._load (internal/modules/cjs/loader.js:769:14)
19:29:35.338 | at Module.require (internal/modules/cjs/loader.js:952:19)
19:29:35.338 | at require (internal/modules/cjs/helpers.js:88:18)
19:29:35.338 | at module.exports (/vercel/workpath0/next.config.js:2:18)
19:29:35.338 | at normalizeConfig (/vercel/workpath0/node_modules/next/dist/next-server/server/config-shared.js:1:1558)
19:29:35.338 | at loadConfig (/vercel/workpath0/node_modules/next/dist/next-server/server/config.js:8:158)
19:29:35.338 | at async Span.traceAsyncFn (/vercel/workpath0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
19:29:35.338 | at async /vercel/workpath0/node_modules/next/dist/build/index.js:2:127
19:29:35.338 | at async Span.traceAsyncFn (/vercel/workpath0/node_modules/next/dist/telemetry/trace/trace.js:5:584)

`

**Comment by sloyer** [comment]
You .ENV file is missing something I believe. Typically thats the error I get at least when I set it up missing a variable.

**Comment by ravewebdev** [comment]
@jahzlariosa it's like due to missing `NEXT_PUBLIC_IMAGE_DOMAINS` in Vercel. An [upcoming PR should address the specific issue with `split()`](https://github.com/WebDevStudios/nextjs-wordpress-starter/pull/379/files#diff-3047d8ec72be294cebb040b913c93497e2a1da6dc68026f031a4ebf0b324656b) as well, but in the meantime you can change line 47 of `/components/atoms/Image/Image.js` to the following:

```
domains = !domains || !domains.length ? [] : domains.split(', ')
```

**Comment by jahzlariosa** [comment]
Awesome! I'll wait for that PR then. Thanks @ravewebdev and @sloyer
