### ISSUE TITLE
Backend Config Issues

### ISSUE THREAD

**Issue by gnortpro** [WebDevStudios/nextjs-wordpress-starter#473]
Thanks team about yours product!
I'm following step by step your guide. 
1. In step `Headless Config --> Options`, I can not find this setting in my dashboard. 
2. My Algolia Search not have `Autocomplete` and `Search Page` menu in your guide.
3. In step config with Algolia Search, I have problem with connection:
`Impossible to connect, please check your Algolia Application Id.`
`We were unable to authenticate you against the Algolia servers with the provided information. Please ensure that you used a valid Application ID and Admin API key.`
I tried with Incognito mode and other browsers but nothing changed. 

Thanks

**Comment by ravewebdev** [comment]
@gnortpro regarding #1, do you see the highlighted menu item shown here? If not, can you confirm the WDS Headless Theme is active on your install?
![Screenshot 2021-06-03 at 11-23-44 Headless Config ‹ Next js WordPress Starter — WordPress](https://user-images.githubusercontent.com/36422618/120686777-96266280-c45e-11eb-89fa-45b0b2ca243e.png)

**Comment by marcosanson** [comment]
Also in my installation I cannot see Headless config menu. I can confirm WDS Theme is installed and active.

**Comment by alexhooley** [comment]
Shows up for me as soon as the Advanced Custom Fields PRO plugin is enabled.

**Comment by ravewebdev** [comment]
@gnortpro @marcosanson do you have the ACF PRO plugin installed and active? If active, does that solve your issues with accessing Headless Config?

**Comment by robclancy** [comment]
Why do we have to use ACF Pro and gravity forms? Doesn't make sense these things are required. I'm going to have to fork and remove these requirements on the plugins I guess.

**Comment by ravewebdev** [comment]
Closing this out as [`wds-headless-core` v2.0.0](https://github.com/WebDevStudios/wds-headless-core/releases/tag/2.0.0) removes the ACF Pro requirement in favor of native WP settings.
