### ISSUE TITLE
Preview links don't show latest revisions for published posts

### ISSUE THREAD

**Issue by iakshay** [WebDevStudios/nextjs-wordpress-starter#537]
**Describe the bug**
On a published post, the preview link of the format - `http://localhost:3000/api/preview?name=another-post&id=39&post_type=post&token=secret` doesn't show latest revision.

**To Reproduce**
1. Publish a post using Gutenberg.
2. Add some more content to the published post, say "test"
3. Open the preview link manually (Preview link in Gutenberg seems broken as reported in #538) - `http://localhost:3000/api/preview?name=new-post&id=52&post_type=post&token=secret`

**Expected behavior**
The preview contents are missing newly added content in step 2. Doing the same on non-headless setup open the preview with test.

**Comment by koraysels** [comment]
yeah i spend an entire day debugging, trying to find where we messed up. conclusion: the previews do not work.. the preview pageprop is set `true` and the previewdata contains something like this ```post:
id: 3
slug: "privacy-policy"
status: "draft"```
 of the previews page/post. but the data is still the old data ...

**Comment by oriandra** [comment]
Try using "revisions" from Wordpress in the gql query so for example for post it will look something like this:
gql`
  query GET_POST_BY_ID(
    $id: ID!
    $idType: PostIdType = SLUG
    $imageSize: MediaItemSizeEnum = LARGE
  ) {
    ${defaultPageData}
    post(id: $id, idType: $idType) {
      ...SinglePostFields
      revisions {
        nodes {
          id
          title
          content
          blocksJSON
          excerpt
        }
      }
    }
  }
  ${singlePostFragment}
`

revisions will return an array of revisions the first item in the array will have your latest "preview" change

**Comment by ravewebdev** [comment]
A fix is now ready for testing via PR #804
