### ISSUE TITLE
Form Fields do not come through Gravity Forms

### ISSUE THREAD

**Issue by sloyer** [WebDevStudios/nextjs-wordpress-starter#569]
**Describe the bug**
Form Fields in Gravity Forms block do not come through, only the submit.
This is happening on two different sites using the latest version of this template but all wordpress plugins are up to date core is still on 5.7

**To Reproduce**
Latest up to date WP plugins, add a form to block on page, select form, click save.
View page, only submit button comes through.

(ignore JSON from above that is for a repeater block)
![Screen Shot 2021-07-23 at 3 46 26 PM](https://user-images.githubusercontent.com/1777605/126850816-2c698a11-ce5b-4393-920f-85608a3dbb12.png)
![Screen Shot 2021-07-23 at 3 53 06 PM](https://user-images.githubusercontent.com/1777605/126850989-0de91856-0a3a-40a0-9243-e75c7fb8e5e1.png)

**Comment by cpramod** [comment]
only shows submit button on my end.  no form fields

**Comment by sloyer** [comment]
> this worked for me after installing graphql for gravity form plugin. https://github.com/harness-software/wp-graphql-gravity-forms

This worked perfectly. Thanks for passing knowledge down.

**Comment by sloyer** [comment]
Ran into another issue, I keep getting this error on submit >.<

"Response not successful: Received status code 500"  

any ideas? This is a fresh install and on an existing

**Comment by cpramod** [comment]
you may have used email field. I see current system doesn't have emailValue set

**Comment by AlopexID** [comment]
Email field fix
```
      case 'EmailField':
        fieldValue.emailValues = {
          value: entryData[fieldName],
          confirmationValue: entryData[fieldName]
        }
        break
```

--Sloyer

**Comment by mrzepecki** [comment]
After installing graphql for gravity form plugin and fixing email field I'm still get "Response not successful: Received status code 500" any ideas?
