### ISSUE TITLE
Issue in blog page when you run generate production build

### ISSUE THREAD

**Issue by shrenikTrukky** [WebDevStudios/nextjs-wordpress-starter#578]
**Describe the bug**
Blog page conflicts with blog post listing when running production build. it's working fine when you run "yarn dev" command. 

**Screenshots**
<img width="1440" alt="Screenshot 2021-07-30 at 9 41 29 AM" src="https://user-images.githubusercontent.com/15668512/127599033-5639b83c-9bf9-440f-adcb-78c8e788abf0.png">
when you run "yarn dev" command it's fetching list and works fine.
<img width="1440" alt="Screenshot 2021-07-30 at 9 43 57 AM" src="https://user-images.githubusercontent.com/15668512/127599191-44e7163b-b5d1-4e5b-b038-837f9630c61c.png">
But when you run "yarn build" it's not show list of blogs because blog page conflicted so archive flag got undefined.

**Comment by soft4net** [comment]
Quickfix: For me It helped to unpublish admin blog page.
But according to NextJS routes order priority it should have no impact on route creation.

**Comment by ravewebdev** [comment]
A fix is ready for testing via PR #805
