### ISSUE TITLE
List of allowed Gutenberg blocks

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#59]
Please put together a list of the most common blocks used on a client project. We'll build those out.

- [x] Create list of common blocks used on projects
- [x] Leverage [Block Manager](https://wordpress.org/plugins/block-manager/) for disabling obscure blocks

**Comment by dcooney** [comment]
@gregrickaby This is done and code has been pushed to WPE.

**Comment by gregrickaby** [comment]
Thank you!
