### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#6]
Need to support routing to and displaying WordPress pages.

https://docs.wpgraphql.com/getting-started/pages/

Example query:

```graphql
query MyQuery {
  page(id: "12", idType: DATABASE_ID) {
    title(format: RENDERED)
    author {
      name
    }
    slug
    content
    seo {
      metaDesc
      metaKeywords
      metaRobotsNofollow
      metaRobotsNoindex
    }
  }
}

```

**Comment by martinDolan** [comment]
I've begun working on this feature. Branch can be found here:
https://github.com/WebDevStudios/nextjs-wordpress-starter/tree/feature/add-pages-6
