### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#7]
Need to support and route to Custom Post Types. Both [CPTUI](https://wordpress.org/plugins/custom-post-type-ui/) and [WP GraphQL CPTUI](https://github.com/wp-graphql/wp-graphql-custom-post-type-ui) plugins are installed.

https://docs.wpgraphql.com/getting-started/custom-post-types/

I created a sample CPT called, "Team" and setup CPTUI + WP GraphQL CPTUI + ACF field

Enable CPT in GraphQL:
![screenshot](https://dl.dropbox.com/s/2aqozulsvvwbvlw/Screenshot%202020-06-26%2011.22.00.png?dl=0)

Enable ACF fields:
![screenshot](https://dl.dropbox.com/s/2fc4st231gnk3i8/Screenshot%202020-06-26%2011.23.56.png?dl=0)

Example query:

```graphql
query MyQuery {
  team_members {
    edges {
      node {
        title
        content
        acf_team_member_title {
          title
        }
      }
    }
  }
}

```

**Comment by asharirfan** [comment]
### Update

I have started working on this issue in the `feature/cpt-pages` branch. I was able to generate a static page to display all the team members successfully.

But I am having trouble writing the WPGraphQL query to dynamically generate the individual team member page.

### Screenshot

![image](https://i.imgur.com/6yyZylS.jpg)

**Comment by gregrickaby** [comment]
@asharirfan Let's connect on Tuesday and rubber 🦆

**Comment by asharirfan** [comment]
@gregrickaby I have figured out the Graphql query myself. And I am successfully able to generate the single pages for the custom post type. I want to discuss how to proceed from this point on with you. Maybe in the WDS Blocks scrum?

### Screenshot

![image](https://i.imgur.com/GWDXkZx.jpg)

**Comment by asharirfan** [comment]
EOD Update:

- Added some styles to the Members archive page
- Separated the member item on archive page to its own component
