### ISSUE TITLE
Very slow dev builds when switching pages etc.. 

### ISSUE THREAD

**Issue by koraysels** [WebDevStudios/nextjs-wordpress-starter#737]
Hi,

Im developing my second website with this starter setup but i am facing very slow dev builds. when switching pages it becomes suuuper sluggish and taken almost 15seconds.. I am running everything locally (also WP) and on an i9 mac pro. 

is there anything that can be done to make the development process less painfully slow ?

thanks.

**Comment by Sameedahmad** [comment]
@koraysels It seems like this issue is from Next.js https://github.com/vercel/next.js/issues/12797#issue-616761815. I completely agree with you the dev builds are extremely slow.
