### ISSUE TITLE
headless-core plugin break hierarchical links in gutenberg admin sidepanel

### ISSUE THREAD

**Issue by koraysels** [WebDevStudios/nextjs-wordpress-starter#778]
Create a normal page, then create another page and set the parent of that new page to any other page. 

Then publish and refresh. If you then try one of the following things the resulting route will be wrong:

- click preview page
- click the permalink link in the sidebar. (the text of the link contains the parent page but the actual href does not.. resulting in a 404)

Consequences: 
our clients cannot preview changes to hierarchical child pages

**Comment by koraysels** [comment]
this line is the culprit!
[this line is the culprit!](https://github.com/WebDevStudios/wds-headless-core/blob/main/inc/links.php#L127)
Line 127 in `links.php`
```php
$response->data['link'] = "{$base_url}/{$post->post_name}";
```

**Comment by koraysels** [comment]
if anyone could merge my PR that would solve this problem completely :)

**Comment by koraysels** [comment]
[this PR](https://github.com/WebDevStudios/nextjs-wordpress-starter/pull/779) also fixes the redirects for the preview links in the next api

**Comment by ravewebdev** [comment]
@koraysels while working on another internal project, we implemented a more comprehensive fix for link replacement. I finally had some time to port those changes to the `wds-headless-core` repo, which you can see here: https://github.com/WebDevStudios/wds-headless-core/pull/4. We're aiming to get this merged in very soon.
