### ISSUE TITLE
Menu is undefined

### ISSUE THREAD

**Issue by AeShevch** [WebDevStudios/nextjs-wordpress-starter#796]
Greetings! Thank you for a great tool!

Please help me figure it out - I'm transferring the site from a local server to a remote one. 
The menu is not displayed on the remote server

On the local server: 
![Снимок экрана 2021-12-21 в 0 25 51](https://user-images.githubusercontent.com/44289476/146834850-04b3d73f-d738-4588-91e4-f81c0a33349b.png)

On a remote server:
menus: undefined

Wordpress on a remote server is a complete copy of the local one - copied through the Duplicator plugin

I replaced the values of WORDPRESS_URL and NEXT AUTO_URL in .env with the URL of the remote server.

Could it be because of an incorrect SSL certificate?
it is self-signed

**Comment by AeShevch** [comment]
oh.. The problem is more serious than I thought - Gutenberg is not working

![Screenshot 2021-12-21 at 21 46 01](https://user-images.githubusercontent.com/44289476/146982588-d4869f2a-ae21-4476-983f-1b1752840331.png)
![Screenshot 2021-12-21 at 21 46 10](https://user-images.githubusercontent.com/44289476/146982592-649b53f0-2a6c-4dbb-9ff9-49aef4f3b192.png)

**Comment by ravewebdev** [comment]
@AeShevch are you seeing any data from WP when connected to the remote server (i.e., are menus the only data missing)? If menus are the only thing missing, then I'd recommend the following troubleshooting steps:
- Double-check that the correct plugins and themes are activated on the remote server and that the defined menu locations in WP match those defined here: https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/ed8cd769b3af657d7a8d813db63a88a8b02e0498/frontend/lib/wordpress/_config/menuLocations.js#L2
- On your remote server in the WP admin dashboard, go to GraphiQL IDE, try the following query, and ensure you're seeing some menu data in response:
```
query GET_MENUS {
  menus {
    nodes {
      locations
      menuItems(first: 100) {
        nodes {
          id
          parentId
          label
          path
          target
          title
        }
      }
    }
  }
}
```
- If you're seeing menus in response to the above query, on the frontend open the file `functions/wordpress/postTypes/processPostTypeQuery.js` and log out `menus` and/or `res.data` after the following line and see what you're getting there: https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/ed8cd769b3af657d7a8d813db63a88a8b02e0498/frontend/functions/wordpress/postTypes/processPostTypeQuery.js#L52

**Comment by AeShevch** [comment]
> *

Thnx for your answer!

It looks like I'm not getting any data at all.
Also, when trying to "Update block registry" in WP GraphQL Gutenberg Admin, I get the error "The response is not a valid JSON response". I don't even know if it's related or not.
It seems to me that the problem is the lack of https on the frontend part. But I don't understand how I can set it up there. The frontend works from docker.

**Comment by ravewebdev** [comment]
@AeShevch can you try the second and third troubleshooting steps above (run the example query in GraphiQL IDE, then log out `res.data` from `processPostTypeQuery.js`)? If the latter doesn't log out at all, then try logging out `error` after this line: https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/ed8cd769b3af657d7a8d813db63a88a8b02e0498/frontend/functions/wordpress/postTypes/processPostTypeQuery.js#L95

**Comment by ravewebdev** [comment]
Closed via https://github.com/WebDevStudios/nextjs-wordpress-starter/issues/799#issuecomment-1001002302
