### ISSUE TITLE
The response is not a valid JSON response.

### ISSUE THREAD

**Issue by AeShevch** [WebDevStudios/nextjs-wordpress-starter#799]
I get the error "The response is not a valid JSON response." when trying update block registry, after changing the permalinks to "/blog/%postname%".
![Screenshot 2021-12-22 at 21 37 47](https://user-images.githubusercontent.com/44289476/147139737-8d555064-c6ce-4e67-9502-0fc088b84f60.png)

![Screenshot 2021-12-22 at 21 38 35](https://user-images.githubusercontent.com/44289476/147139834-9208473b-c65a-48bb-a682-dff86701a120.png)

![Screenshot 2021-12-22 at 21 38 50](https://user-images.githubusercontent.com/44289476/147139856-aacb5511-2e89-4f0b-bd5d-85f1852c0130.png)

Works well when I change back:

![Screenshot 2021-12-22 at 21 40 41](https://user-images.githubusercontent.com/44289476/147140029-715ebd69-26cd-4620-aca6-95698218226e.png)

![Screenshot 2021-12-22 at 21 42 41](https://user-images.githubusercontent.com/44289476/147140234-1c117112-83fe-4719-9cc7-43730634a89a.png)

![Screenshot 2021-12-22 at 21 41 45](https://user-images.githubusercontent.com/44289476/147140143-ef9b6381-b98b-480f-acf8-9d04b32fb13c.png)

**Comment by ravewebdev** [comment]
@AeShevch have you tested by disabling all plugins/themes (except WP GraphQL & WP GraphQL Gutenberg) to see if the issue goes away? If it does, then try enabling plugins/themes one at a time until the issue reappears, and let us know which one triggered the error.

**Comment by AeShevch** [comment]
> @AeShevch have you tested by disabling all plugins/themes (except WP GraphQL & WP GraphQL Gutenberg) to see if the issue goes away? If it does, then try enabling plugins/themes one at a time until the issue reappears, and let us know which one triggered the error.

Yes, I tried. Same result

**Comment by ravewebdev** [comment]
@AeShevch do you mean the same error occurred with all custom plugins/themes disabled except WP GraphQL & WP GraphQL Gutenberg? If so, then that sounds like an issue with the WP GraphQL Gutenberg plugin.

**Comment by AeShevch** [comment]
> @AeShevch do you mean the same error occurred with all custom plugins/themes disabled except WP GraphQL & WP GraphQL Gutenberg? If so, then that sounds like an issue with the WP GraphQL Gutenberg plugin.

Yes, turned everything off

![Screenshot 2021-12-23 at 22 24 27](https://user-images.githubusercontent.com/44289476/147283975-00ef72ef-3762-487a-8260-876e6c7d73fc.png)
![Screenshot 2021-12-23 at 22 27 56](https://user-images.githubusercontent.com/44289476/147284253-4c6c0e9e-fff3-4984-8327-89251deb6fb0.png)
!

But I don't think it's the plugin. I reinstalled wp again yesterday and went through the whole setup process according to the instructions - the same thing.

**Comment by AeShevch** [comment]
Plus a local project, with the same plugin, works fine

**Comment by AeShevch** [comment]
If I return the Permalink to the default value, the request is successful, but at a completely different url - 
`/index.php?rest_route=%2Fwp-graphql-gutenberg%2Fv1%2Fblock-registry&_locale=user`
instead of 
`/wp-com/wp-graphql-gutenberg/v1/block-registry?_locale=user`

**Comment by AeShevch** [comment]
In addition, I just tried to enable a standard template - all pages except the main one return 404, if Permalink is set to /blog/%postname%/

**Comment by ravewebdev** [comment]
@AeShevch did you try with a non-headless theme enabled? If so, and none of the WDS themes/plugins are enabled, then I don't think the issue is coming from our code. If the issue goes away once the WDS theme is disabled, let us know, and we can investigate further.

**Comment by AeShevch** [comment]
> 

Thank you for your help! The problem was the wrong nginx settings, now everything works.

**Comment by ravewebdev** [comment]
@AeShevch glad to hear it's resolved. Did that fix resolve your other issue as well (#796)?

**Comment by AeShevch** [comment]
@ravewebdev Yes! It fixed everything!
