### ISSUE TITLE
Columns don't break to a single column on mobile

### ISSUE THREAD

**Issue by itsamoreh** [WebDevStudios/nextjs-wordpress-starter#885]
### Discussed in https://github.com/WebDevStudios/nextjs-wordpress-starter/discussions/710

<div type='discussions-op-text'>

<sup>Originally posted by **ThatGuySam** October  4, 2021</sup>
The Columns component and block don't currently break into single columns for small/mobile screens. 

Perhaps this is on purpose but it should be a simple change [here](https://github.com/WebDevStudios/nextjs-wordpress-starter/blob/canary/frontend/components/atoms/Columns/Columns.module.css)

```
.columns {
  @apply grid gap-8 grid-cols-3;

  &.columns-1 {
    @apply grid-cols-1;
  }

  &.columns-2 {
    @apply grid-cols-2;
  }

 ...etc
```

Becomes

```
.columns {
  @apply grid gap-8 lg:grid-cols-3;

  &.columns-1 {
    @apply lg:grid-cols-1;
  }

  &.columns-2 {
    @apply lg:grid-cols-2;
  }

 ...etc
```
</div>

I can replicate this and I agree, columns should all break to a single column on mobile.

**Comment by itsamoreh** [comment]
Here's a quick video of the issue. The three columns should be a single full width column on mobile.

**Comment by itsamoreh** [comment]
I thought this would be a pretty quick fix by just setting the columns to `flex-col` on mobile and `flex-row` on md (tablet). It works but, the column is getting an inline style of `width: 50%;`. This means columns don't stretch to full width on mobile.

https://user-images.githubusercontent.com/12365909/150546455-f4969982-6725-4a1c-a624-ceedbd5f92c9.mov


Does anyone know where this inline style is coming from?

**Comment by johnrobertmcc** [comment]
@itsamoreh The width is being set to '50%' in `BlockColumns.js` as a default inside of the innerBlock mapping (ln 56 below). I am unsure what the purpose of this is, so I'm cautious to remove it. 
![image](https://user-images.githubusercontent.com/66800579/155211454-a04fb237-f089-4a06-a4f8-ce05534dbe58.png).

We could either: 
a) remove the fallback '50%' inside the mapping,
or b) set the width of the `.column` to `100% !important;` inside of `Columns.module.css`

Both result in the full width on mobile:
![image](https://user-images.githubusercontent.com/66800579/155211855-f89b4aeb-22bf-4616-bce0-a5a11b5d250a.png)

CC: @gregrickaby
