### ISSUE TITLE
Failure to load JSON Data

### ISSUE THREAD

**Issue by sloyer** [WebDevStudios/nextjs-wordpress-starter#974]
**Describe the bug**
Hey there,

This issue is happening on quite a few sites using this amazing boiler plate. 
Sometimes randomly pages with 404 with their JSON data and it will take a build or two for it to start working again. 

I am thinking this may be tied to this issue in the [discussion](https://github.com/WebDevStudios/nextjs-wordpress-starter/discussions/968) board. 

Hosting WP is a cloudways Digital ocean droplet. 4GB Ram, 80GB SSD 4TB transfer, 2 core proccessor. During build this will be maxed out at 100%

This isn't just related to the current revision of this, we have sites using the current plugin separated and with the plugins still in all in one. 

Attached is an image of what we will see during this issue.
![Screen Shot 2022-03-18 at 3 51 18 PM](https://user-images.githubusercontent.com/1777605/159098559-c6f158e4-49ed-45a5-9e08-251e506a6d71.png)

**Comment by LabStormGroup** [comment]
Im getting the same issue on JSON come back with `An error occurred while trying to retrieve data` I believe this is coming from Graphql if post data not found. 
the strange thing for me is that its only happening when I use the navigation (using Link)  but when I reload the page its coming up alright.
for Wordpress I use AWS LightSale 160 gig RAM 4vCPU, 6TB transfer

**Comment by sloyer** [comment]
Upgrading to an 8GB seems to have resolved this 

When the deployment is been done as we discussed above that the cpu resources are been utilized and if the server isn't upto the mark it exhausts and the deployment gets failed. The above server was 8GB and it has the strength of tackling such queries and deployment. However, For checking the load we recommend that the load average must be less than the number of cores of the cpu and you can currently see that its 0.55 and the cores you have on the server are 2.

Spendy but it works for now.
